spring.application.name=budget-ai

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
